#!/bin/bash 

apt-get install python-dev python-pip python-virtualenv virtualenvwrapper mongodb python-pymongo varnish git nginx unzip libcurl4-openssl-dev screen libxml2-dev libxslt1-dev psmisc libjpeg8-dev libfreetype6-dev lsof bind

mkdir -p /var/virtualenvs
export WORKON_HOME=/var/virtualenvs
echo 'export WORKON_HOME=/var/virtualenvs' >> /root/.bashrc
echo 'export PS1="PRODUCTION \w$ "' >> /root/.bashrc
echo workon imeveryone >> /root/.bashrc
echo cdvirtualenv >> /root/.bashrc

Add ssh keys
scp -rv -p 443 .ssh/id_rsa* root@imeveryone.com:.ssh

# Creating Reo 
cd /var/virtualenvs
git clone git@github.com:mikemaccana/imeveryone.git

# Updating Repo
cd imeveryone
git pull origin master

mkvirtualenv imeveryone

git pull origin master
ln -s imeveryone-prod.conf imeveryone.conf

imeveryone $ scp -rv db/* root@microsites.net:/var/virtualenvs/imeveryone/db

workon imeveryone
pip install tornado configobj lxml BeautifulSoup PIL oembed recaptcha-client akismet poster  ipython ipdb
env ARCHFLAGS="-arch x86_64" pip install pycurl


mkdir static/cache

# nginx -t -c /var/virtualenvs/imeveryone/deploy/nginx.conf